import { test, expect } from 'vitest';
import { Parser } from '../../parser/gcode-parser';
import { Interpreter } from '../../interpreter';
import { Job } from '../../job';

// A minimal PrusaSlicer-style program: two layers at Z 0.2 and 0.4, each with a
// short extrusion move. Layer boundaries come from the ;LAYER_CHANGE/;Z comments.
const PRUSA_LINES = [
  '; generated by PrusaSlicer 2.9.2',
  'M83',
  ';LAYER_CHANGE',
  ';Z:0.2',
  ';HEIGHT:0.2',
  'G1 X0 Y0 Z0.2',
  'G1 X10 Y10 E1',
  'G1 X20 Y0 E1',
  ';LAYER_CHANGE',
  ';Z:0.4',
  ';HEIGHT:0.2',
  'G1 X0 Y0 Z0.4',
  'G1 X10 Y10 E1'
];
const PRUSA_GCODE = PRUSA_LINES.join('\n');

// No slicer fingerprint: should fall back to tolerance-based layer detection.
const PLAIN_GCODE = ['M83', 'G1 X0 Y0 Z0.2', 'G1 X10 Y10 E1', 'G1 X0 Y0 Z0.4', 'G1 X10 Y10 E1'].join('\n');

test('parser extracts slicer metadata and detects the slicer', () => {
  const { metadata } = new Parser().parseGCode(PRUSA_GCODE);

  expect(metadata.slicerName).toBe('PrusaSlicer');
  expect(metadata.layerMetadata).toHaveLength(2);
  expect(metadata.layerMetadata?.[0].z).toBeCloseTo(0.2);
  expect(metadata.layerMetadata?.[1].z).toBeCloseTo(0.4);
});

test('parser extracts extrusion dimension events at their line indices', () => {
  const { metadata } = new Parser().parseGCode(PRUSA_GCODE);

  // The ;HEIGHT: lines double as layer metadata and as dimension events.
  expect(metadata.extrusionDimensions).toEqual([
    { height: 0.2, lineIndex: 4 },
    { height: 0.2, lineIndex: 10 }
  ]);
});

test('extrusion dimension metadata reaches the paths end-to-end', () => {
  const { commands, metadata } = new Parser().parseGCode(PRUSA_GCODE);

  const job = new Job();
  job.metadata = metadata;
  new Interpreter().execute(commands, job);

  // every extrusion follows a ;HEIGHT:0.2 comment; no ;WIDTH: was announced
  for (const path of job.extrusions) {
    expect(path.lineHeight).toBe(0.2);
    expect(path.extrusionWidth).toBeUndefined();
  }
});

test('accumulates dimension events with whole-file line indices when parsing in chunks', () => {
  const splitAt = PRUSA_LINES.indexOf(';LAYER_CHANGE', PRUSA_LINES.indexOf(';LAYER_CHANGE') + 1);
  const chunks = [PRUSA_LINES.slice(0, splitAt).join('\n'), PRUSA_LINES.slice(splitAt).join('\n')];

  const parser = new Parser();
  for (const chunk of chunks) parser.parseGCode(chunk);

  // The second event sits in the second chunk; its chunk-local index must be
  // shifted by the lines parsed before it, matching the one-shot result.
  expect(parser.metadata.extrusionDimensions).toEqual([
    { height: 0.2, lineIndex: 4 },
    { height: 0.2, lineIndex: 10 }
  ]);
});

test('slicer metadata drives job layer indexing end-to-end', () => {
  const { commands, metadata } = new Parser().parseGCode(PRUSA_GCODE);

  const job = new Job();
  job.metadata = metadata; // must forward layer metadata to the indexer
  new Interpreter().execute(commands, job);

  expect(job.metadata).toBe(metadata);
  expect(job.layers).toHaveLength(2);
  expect(job.layers[0].z).toBeCloseTo(0.2);
  expect(job.layers[1].z).toBeCloseTo(0.4);
  // Each layer should hold the extrusion(s) sliced at its Z.
  expect(job.layers[0].paths.length).toBeGreaterThan(0);
  expect(job.layers[1].paths.length).toBeGreaterThan(0);
});

test('setting job metadata after construction still forwards to the indexer', () => {
  const { commands, metadata } = new Parser().parseGCode(PRUSA_GCODE);

  // Job is created before metadata exists (as in WebGLPreview); assigning it
  // later must still enable metadata-based indexing.
  const job = new Job();
  new Interpreter(); // no-op, mirrors real construction order
  job.metadata = metadata;
  new Interpreter().execute(commands, job);

  expect(job.layers).toHaveLength(2);
});

test('job falls back to tolerance detection when no metadata is present', () => {
  const { commands, metadata } = new Parser().parseGCode(PLAIN_GCODE);

  expect(metadata.slicerName).toBeUndefined();
  expect(metadata.layerMetadata).toBeUndefined();

  const job = new Job();
  job.metadata = metadata;
  new Interpreter().execute(commands, job);

  // Two distinct Z heights → two tolerance-detected layers.
  expect(job.layers).toHaveLength(2);
});

test('drives the job layer index identically when parsing in chunks', () => {
  // Single-shot reference flow.
  const singleParse = new Parser().parseGCode(PRUSA_GCODE);
  const singleJob = new Job();
  singleJob.metadata = singleParse.metadata;
  new Interpreter().execute(singleParse.commands, singleJob);

  // Chunked flow: one Parser, one Job, one Interpreter across chunks.
  const splitAt = PRUSA_LINES.indexOf(';LAYER_CHANGE', PRUSA_LINES.indexOf(';LAYER_CHANGE') + 1);
  const chunks = [PRUSA_LINES.slice(0, splitAt).join('\n'), PRUSA_LINES.slice(splitAt).join('\n')];

  const parser = new Parser();
  const job = new Job();
  const interpreter = new Interpreter();
  for (const chunk of chunks) {
    const { commands, metadata } = parser.parseGCode(chunk);
    job.metadata = metadata;
    interpreter.execute(commands, job);
  }

  expect(job.layers).toHaveLength(singleJob.layers.length);
  job.layers.forEach((layer, i) => {
    expect(layer.z).toBeCloseTo(singleJob.layers[i].z);
  });
  expect(job.layers[0].z).toBeCloseTo(0.2);
  expect(job.layers[1].z).toBeCloseTo(0.4);
});

const DIMENSION_LINES = [
  '; generated by PrusaSlicer 2.9.2',
  'M83',
  'G1 X10 E1',
  ';WIDTH:0.9',
  ';HEIGHT:0.2',
  'G1 X20 E1',
  '',
  ';WIDTH:0.3',
  ';HEIGHT:0.1',
  'G1 X30 E1'
];

test('filtered commands retain the dimensions at their source lines', () => {
  const { commands, metadata } = new Parser().parseGCode(DIMENSION_LINES);
  const job = new Job();
  job.metadata = metadata;
  new Interpreter().execute(
    commands.filter((command) => command.gcode),
    job
  );

  expect(job.extrusions.map((path) => [path.extrusionWidth, path.lineHeight])).toEqual([
    [undefined, undefined],
    [0.9, 0.2],
    [0.3, 0.1]
  ]);
});

test('reordered commands replay dimensions and clear events after their source line', () => {
  const { commands, metadata } = new Parser().parseGCode(DIMENSION_LINES);
  const job = new Job();
  job.metadata = metadata;
  new Interpreter().execute([commands[1], commands[9], commands[5], commands[2], commands[9]], job);

  expect(job.extrusions.map((path) => [path.extrusionWidth, path.lineHeight])).toEqual([
    [0.3, 0.1],
    [0.9, 0.2],
    [undefined, undefined],
    [0.3, 0.1]
  ]);
});
