import { test, expect } from 'vitest';
import { detectSlicer, parseSlicerMetadata, getAvailableParsers } from '../../parser/slicer-detector';
import { GCodeCommand } from '../../parser/gcode-parser';

function createCommand(src: string, comment?: string, params = {}): GCodeCommand {
  return new GCodeCommand(0, src, 'g1', params, comment);
}

test('detectSlicer detects PrusaSlicer', () => {
  const commands = [
    createCommand('; generated by PrusaSlicer 2.9.2', 'generated by PrusaSlicer 2.9.2'),
    createCommand('G1 X0 Y0')
  ];

  const parser = detectSlicer(commands);

  expect(parser).not.toBeNull();
  expect(parser!.slicerName).toBe('PrusaFamily');
  expect(parser!.detectSlicerName(commands.filter((cmd) => cmd.comment))).toBe('PrusaSlicer');
});

test('detectSlicer detects Cura', () => {
  const commands = [
    createCommand(';Generated with Cura_SteamEngine 5.0', 'Generated with Cura_SteamEngine 5.0'),
    createCommand('G1 X0 Y0')
  ];

  const parser = detectSlicer(commands);

  expect(parser).not.toBeNull();
  expect(parser!.slicerName).toBe('Cura');
});

test('detectSlicer returns null for unknown slicer', () => {
  const commands = [
    createCommand('; Generated by UnknownSlicer', 'Generated by UnknownSlicer'),
    createCommand('G1 X0 Y0')
  ];

  const parser = detectSlicer(commands);

  expect(parser).toBeNull();
});

test('detectSlicer prioritizes the Prusa family when both patterns match', () => {
  const commands = [
    createCommand(';LAYER_CHANGE', 'LAYER_CHANGE'), // Prusa family pattern
    createCommand(';LAYER:0', 'LAYER:0'), // Cura pattern
    createCommand('G1 X0 Y0')
  ];

  const parser = detectSlicer(commands);

  expect(parser).not.toBeNull();
  expect(parser!.slicerName).toBe('PrusaFamily'); // Should pick first matching parser
});

test('parseSlicerMetadata parses PrusaSlicer metadata', () => {
  const commands = [
    createCommand(';LAYER_CHANGE', 'LAYER_CHANGE'),
    createCommand(';Z:0.3', 'Z:0.3'),
    createCommand(';HEIGHT:0.3', 'HEIGHT:0.3'),
    createCommand('G1 X0 Y0 Z0.3 E1')
  ];

  const result = parseSlicerMetadata(commands, detectSlicer(commands));

  expect(result.slicerName).toBe('PrusaFamily');
  expect(result.layers).toHaveLength(1);
  expect(result.layers[0]).toEqual({
    layerIndex: 0,
    z: 0.3,
    height: 0.3,
    lineIndex: 0
  });
});

test('parseSlicerMetadata parses Cura metadata', () => {
  const commands = [createCommand(';LAYER:0', 'LAYER:0'), createCommand('G1 X0 Y0 Z0.3 E1', undefined, { z: 0.3 })];

  const result = parseSlicerMetadata(commands, detectSlicer(commands));

  expect(result.slicerName).toBe('Cura');
  expect(result.layers).toHaveLength(1);
  expect(result.layers[0]).toEqual({
    layerIndex: 0,
    z: 0.3,
    lineIndex: 0
  });
});

test('parseSlicerMetadata returns empty result for unknown slicer', () => {
  const commands = [createCommand('; Some unknown comment', 'Some unknown comment'), createCommand('G1 X0 Y0')];

  const result = parseSlicerMetadata(commands);

  expect(result.slicerName).toBeUndefined();
  expect(result.layers).toHaveLength(0);
});

test('getAvailableParsers returns all parsers', () => {
  const parsers = getAvailableParsers();

  expect(parsers).toHaveLength(4);
  expect(parsers[0].slicerName).toBe('PrusaFamily');
  expect(parsers[1].slicerName).toBe('Simplify3D');
  expect(parsers[2].slicerName).toBe('Slic3r');
  expect(parsers[3].slicerName).toBe('Cura');
});

test('parseSlicerMetadata handles empty commands array', () => {
  const result = parseSlicerMetadata([]);

  expect(result.slicerName).toBeUndefined();
  expect(result.layers).toHaveLength(0);
});

test('parseSlicerMetadata handles commands without comments', () => {
  const commands = [createCommand('G1 X0 Y0'), createCommand('G1 X10 Y10')];

  const result = parseSlicerMetadata(commands);

  expect(result.slicerName).toBeUndefined();
  expect(result.layers).toHaveLength(0);
});

test('a Slic3r file carrying WIDTH comments is still detected as Slic3r', () => {
  // Slic3r's verbose gcode emits the same ;WIDTH:/;HEIGHT: comments as the
  // PrusaSlicer family it fathered. The PrusaFamily parser is tried first, so
  // treating those comments as an identification pattern claimed the file
  // before the Slic3r parser was ever consulted, losing its layer markers.
  const commands = [
    createCommand('; generated by Slic3r 1.3.0 on 2023-01-01', 'generated by Slic3r 1.3.0 on 2023-01-01'),
    createCommand('; move to next layer (1)', 'move to next layer (1)'),
    createCommand(';WIDTH:0.45', 'WIDTH:0.45'),
    createCommand(';HEIGHT:0.2', 'HEIGHT:0.2')
  ];

  expect(detectSlicer(commands)?.slicerName).toBe('Slic3r');
});
